### ISSUE TITLE
目录的图标不会随着网页的上下移动而移动

### ISSUE THREAD

**Issue by gaochun** [gaochun/volunpedia#3]
目录的图标不会随着网页的上下移动而移动，一直固定，造成阅读不便，希望目录图标可以随着页面上下移动而移动。

**Comment by zhangqiwei19820105** [comment]
@gaochun 我把这个bug reopen了，现在出了个新的问题，"目录"图标不仅会随着网页上下移动而同步漂移，页面左右移动的时候也会漂。
![image](https://cloud.githubusercontent.com/assets/10906630/6147018/f52a5aba-b22d-11e4-814a-1d9dc8fccc40.png)

**Comment by gaochun** [comment]
@zhangqiwei19820105 水平移动的问题已经fix了。在页面垂直scroll的时候，我的理解是当“目录”随页面往上方走到要消失的时候，它应该保持在最顶端不再往上走了。

**Comment by gaochun** [comment]
@zhangqiwei19820105 不知道这个bug的描述是不是有问题，按ppt里的描述，这个bug本身是不存在的。
